routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route for login
Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('auth/login', 'Auth\LoginController@login');
Route::get('auth/logout', ['as' => 'logout', 'uses' =>  'Auth\LoginController@logout']);


//Route for registartion
Route::get('auth/register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
Route::post('auth/register', 'Auth\RegisterController@register');

// Password reset routes
Route::get('password/reset/{token?}', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email','Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
/*
Route::get('password/reset/{token?}', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email','Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');*/

Route::resource('categories', 'CategoryController', ['except' => ['create']]);

Route::resource('tags', 'TagController', ['except' => ['create']]);

//comment
Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);
Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);
Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);
Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);



  Route::get('blog/{slug}', ['as' => 'blog.singlepost', 'uses' => 'BlogController@getSingle'])
  ->where('slug', '[\w\d\-\_]+'); // or where('slug', '@[\w\d\-\_]+');

  Route::get('about', 'PagesController@getAbout');


  Route::get('ecommerce', 'PagesController@getEcommerce');

  Route::get('blogs', 'BlogController@getIndex');

  //Route::get('blog', 'PagesController@getBlog');

  Route::get('popularposts', ['as' => 'blogs.popularposts', 'uses' => 'BlogController@getPopularposts']);

  Route::get('contact', 'PagesController@getContact');

  Route::post('contact', ['as' =>'contact.post', 'uses' =>'PagesController@postContact']);

  Route::get('project', 'PagesController@getProject');

  Route::get('/', 'PagesController@getIndex');

  Route::resource('posts', 'PostController');

 

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
  public function posts()
  {

    return $this->belongsToMany('App\Tag');
  }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Session;
use App\Post;

class TagController extends Controller
{

  public function __construct() {

    $this->middleware('auth');
  }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      //grabe all of the the tag
         $tags = Tag::all();

         //dispaly all the tags
         return view('tags.index')->withTags($tags);

    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
          "name" => 'required|max:255'
            ));
          $tag = new Tag;
          $tag->name = $request->name;
          $tag->save();

          Session::flash('success', 'New tag has been successfuly created!');

          return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $tag = Tag::find($id);
         return view('tags.show')->withTag($tag);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

      $tag = Tag::find($id);
      return view('tag.edit')->withTag($tag);


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->posts->detach();

        $tag->delete();

        Session::flash('success', 'The blog has been successfuly deleted!');

        return redirect()->route(tags.index);
    }
}

resources/views/tags/index.blade.php
@extends('main')


@section('title',  '|All Tags')




@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-9">

      <h1>Tags</h1>

        <table class="table">
          <thead>
              <tr>
                <th>#</th>

                <th>Name</th>

              </tr>
          </thead>
          @foreach ($tags as $tag)
          <tbody>
            <tr>
            <td>{{$tag->id}}</td>
            <td><a href=" {{ route('tags.show', $tag->id) }}">{{ $tag->name }} </a></td>
          </tr>
          @endforeach
          </tbody>

        </table>

    </div>

    <div class="col-md-3">
      <div class="well">
        {!! Form::open (['route' => 'tags.store', 'method' => 'POST']) !!}
        <h2> New Tags</h2>
        {{ Form::label('name', 'Name:') }}
        {{ form::text('name', null, ['calss' => 'form-control' ])}}

        {{ form::submit('Create new Tag', ['class' => 'btn btn-primary btn-block form-spacing-top' ])}}


      {!! form::close() !!}
      </div>
    </div>
  </div>

</div>
@endsection

resources/views/tags/show.blade.php
@extends('main')

@section('title', "| $tag->name  Tag")

@section('content')

  <div class="row">
    <div class="col-md-8">
 <h1> {{ $tag->name}} Tag  </h1>
    </div>


      <div class="col-md-4">
        <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-primary pull-right btn-block" style="margin-top:20px;">Edit</a>
      </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>title</th>
            <th>Tags</th>
            <th> </th>
          </tr>
        </thead>
        <tbody>
        <p> All the post along with tag go here
       </tbody>
     </table>
    </div>
  </div>




@endsection