routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route for login
Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('auth/login', 'Auth\LoginController@login');
Route::get('auth/logout', ['as' => 'logout', 'uses' =>  'Auth\LoginController@logout']);


//Route for registartion
Route::get('auth/register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
Route::post('auth/register', 'Auth\RegisterController@register');

// Password reset routes
Route::get('password/reset/{token?}', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email','Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
/*
Route::get('password/reset/{token?}', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email','Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');*/

Route::resource('categories', 'CategoryController', ['except' => ['create']]);

Route::resource('tags', 'TagController', ['except' => ['create']]);

//comment
Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);
Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);
Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);
Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);



  Route::get('blog/{slug}', ['as' => 'blog.singlepost', 'uses' => 'BlogController@getSingle'])
  ->where('slug', '[\w\d\-\_]+'); // or where('slug', '@[\w\d\-\_]+');

  Route::get('about', 'PagesController@getAbout');


  Route::get('ecommerce', 'PagesController@getEcommerce');

  Route::get('blogs', 'BlogController@getIndex');

  //Route::get('blog', 'PagesController@getBlog');

  Route::get('popularposts', ['as' => 'blogs.popularposts', 'uses' => 'BlogController@getPopularposts']);

  Route::get('contact', 'PagesController@getContact');

  Route::post('contact', ['as' =>'contact.post', 'uses' =>'PagesController@postContact']);

  Route::get('project', 'PagesController@getProject');

  Route::get('/', 'PagesController@getIndex');

  Route::resource('posts', 'PostController');

 

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class BlogController extends Controller
{

    public function getIndex(){
      $posts = Post::orderBy('created_at', 'desc')->paginate(4);
      return View('blog.blogs')->withPosts($posts);


    }

    public function getPopularposts(){
      $popularposts = Post::get()->sortByDesc('view_count');
      /*Post::orderBy('view_count', 'DESC')->take(5);*/
      return View('blog.popularposts')->withPopularposts($popularposts);
    }



    public function getSingle($slug) {
      // fetch from the DB based on slug
      $post = Post::where('slug', '=', $slug)->first();
      // return the view and pass in the post object

      return View('blog.singlepost')->withPost($post);
    }
}

resources/views/partials/_footer.blade.php
<p class="text-center" > &copy; VoilaExpress 2017 -  ALL right reserved! </p>

resources/views/partials/_head.blade.php
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>VoilaExpress @yield('title')</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {{ Html::style('css/styles.css') }}

    @yield('stylesheets')
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

resources/views/partials/_javascript.blade.php
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

resources/views/partials/_messages.blade.php
@if (Session::has('success'))

<div class="alert alert-success" role="alert">
  <strong>Success:</strong> {{ Session::get('success') }}
</div>
@endif

@if (count ($errors) > 0)

<div class="alert alert-danger" role="alert">
  <storage> Errors: </strong>
    <ul>
    @foreach ($errors->all() as $error)

      <li> {{ $error}} </li>
      @endforeach
</ul>
</div>

</div>
@endif

resources/views/partials/_nav.blade.php
<!-- default bootstrap navbar -->
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">VoilaExpress.com</a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
       <li class="{{ Request::is ('/') ? "active" : ""}} "><a href="/">Home <span class="sr-only">(current)</span></a></li>
       <li class="{{ Request::is ('about') ? "active" : ""}} "><a href="/about">About</a></li>
       <li class="{{ Request::is ('blogs') ? "active" : ""}} "><a href="/blogs">Blog</a></li>
       <li class="{{ Request::is ('contact') ? "active" : ""}} "><a href="/contact">Contact</a></li>
       <li class="{{ Request::is ('project') ? "active" : ""}} "><a href="/project">Projects</a></li>
       <li class="{{ Request::is ('ecommerce') ? "active" : ""}} "><a href="/ecommerce">E-Commerce</a></li>


     </ul>
  <!--   <form class="navbar-form navbar-left">
       <div class="form-group">
         <input type="text" class="form-control" placeholder="Search">
       </div>
       <button type="submit" class="btn btn-default">Submit</button>
     </form>-->
     <ul class="nav navbar-nav navbar-right">
      @if(Auth::check())
       <li class="dropdown">

         <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {{ Auth::user()-> name }} <span class="caret"></span></a>
         <ul class="dropdown-menu">
           <li><a href="{{route('posts.index') }}">Posts</a></li>
           <li><a href="{{route('categories.index') }}">Categories</a></li>
              <li><a href="{{route('tags.index') }}">Tag</a></li>

           <li role="separator" class="divider"></li>
           <li><a href="{{ route('logout') }}">Logout</a></li>
         </ul>
       </li>
       @else
       <li class="dropdown">
         <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
       <ul class="dropdown-menu">
       <li><a href="{{ route('login') }}">Login</a></li>
       <li><a href="{{ route('register') }}">Register</a></li>
        </ul>
      </li>
       @endif
     </ul>
   </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>